name: UnitTests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dotnet 6.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"
          include-prerelease: True
      - name: build
        run: dotnet build Bee.Dotnet.sln

      - name: Bee.Tests
        run: dotnet test Bee.Dotnet.sln

